In [1]:
import os
import json
import pandas as pd
import pymysql 
from datetime import datetime
import plotly.express as px
import requests

# aggregated

In [2]:
#agg_transaction

file1="C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/aggregated/transaction/country/india/state"
agg_tran_state=os.listdir(file1)

columns1 ={'states':[],'years':[],'quarters':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

for state in agg_tran_state:
    current_states=os.path.join(file1,state)
    agg_year_list=os.listdir(current_states)
    

    for year in agg_year_list:
        current_year=os.path.join(current_states,year)
        agg_file_list=os.listdir(current_year)
    
        for file in agg_file_list:
            current_file=os.path.join(current_year,file)
            data=open(current_file)
    
            f=json.load(data)
            for i in f['data']['transactionData']:
                name=i['name']
                count=i['paymentInstruments'][0]['count']
                amount=i['paymentInstruments'][0]['amount']
                columns1['Transaction_type'].append(name)
                columns1['Transaction_count'].append(count)
                columns1['Transaction_amount'].append(amount)
                columns1['states'].append(state)
                columns1['years'].append(year)
                columns1['quarters'].append(int(file.strip('.json')))

agg_transaction =pd.DataFrame(columns1)
agg_transaction['states']=agg_transaction['states'].str.replace('-',' ')
agg_transaction['states']=agg_transaction['states'].str.title()
agg_transaction['states']=agg_transaction['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

In [3]:
#agg_user

file2 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/aggregated/user/country/india/state"
agg_user_state=os.listdir(file2)

columns2 ={'states':[],'years':[],'quarters':[],'Brand':[],'Transaction_count':[],'Percentage':[]}

for state in agg_user_state:
    current_states = os.path.join(file2,state)
    agg_user_year = os.listdir(current_states)
    
    for year in agg_user_year:
        current_year = os.path.join(current_states,year)
        agg_user_file = os.listdir(current_year)
        
        for file in agg_user_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            f2 = json.load(data)
            
            try:
                for i in f2['data']['usersByDevice']:
                    brand = i['brand']
                    count = i['count']
                    percentage = i['percentage']
                    columns2['Brand'].append(brand)
                    columns2['Transaction_count'].append(count)
                    columns2['Percentage'].append(percentage)
                    columns2['states'].append(state)
                    columns2['years'].append(year)
                    columns2['quarters'].append(int(file.strip('.json')))
        
            except:
                pass

agg_user =pd.DataFrame(columns2)
agg_user['states']=agg_user['states'].str.replace('-',' ')
agg_user['states']=agg_user['states'].str.title()
agg_user['states']=agg_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')
agg_user['Percentage'] = (agg_user['Percentage'] * 100).round().astype(int)

In [4]:
#agg_insurance

file3 = 'C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/aggregated/insurance/country/india/state'
agg_insur_state=os.listdir(file3)

columns3 ={'states':[],'years':[],'quarters':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

for state in agg_insur_state:
    current_states = os.path.join(file3,state)
    agg_insur_year = os.listdir(current_states)
    
    for year in agg_insur_year:
        current_year = os.path.join(current_states,year)
        agg_insur_file = os.listdir(current_year)
        
        for file in agg_insur_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            f3 = json.load(data)
            for i in f3['data']['transactionData']:
                name=i['name']
                count=i['paymentInstruments'][0]['count']
                amount=i['paymentInstruments'][0]['amount']
                columns3['Transaction_type'].append(name)
                columns3['Transaction_count'].append(count)
                columns3['Transaction_amount'].append(amount)
                columns3['states'].append(state)
                columns3['years'].append(year)
                columns3['quarters'].append(int(file.strip('.json')))
                
agg_insurance = pd.DataFrame(columns3)
agg_insurance['states']=agg_insurance['states'].str.replace('-',' ')
agg_insurance['states']=agg_insurance['states'].str.title()
agg_insurance['states']=agg_insurance['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

# map

In [5]:
#map_transcation

path1 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/map/transaction/hover/country/india/state"
map_tran_state = os.listdir(path1)

columns4 ={'states':[],'years':[],'quarters':[],'District_Name':[],'Transaction_count':[],'Transaction_amount':[]}

for state in map_tran_state:
    current_states = os.path.join(path1,state)
    map_tran_year = os.listdir(current_states)
    
    for year in map_tran_year:
        current_year = os.path.join(current_states,year)
        map_tran_file = os.listdir(current_year)
        
        for file in map_tran_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            p1 = json.load(data)
            
            for i in p1['data']['hoverDataList']:
                district_name = i['name']
                count = i['metric'][0]['count']
                amount =i['metric'][0]['amount']
                columns4['District_Name'].append(district_name)
                columns4['Transaction_count'].append(count)
                columns4['Transaction_amount'].append(amount)
                columns4['states'].append(state)
                columns4['years'].append(year)
                columns4['quarters'].append(int(file.strip('.json')))
                
map_transaction = pd.DataFrame(columns4)
map_transaction['states']=map_transaction['states'].str.replace('-',' ')
map_transaction['states']=map_transaction['states'].str.title()
map_transaction['states']=map_transaction['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

In [6]:
#map_user

path2 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/map/user/hover/country/india/state"
map_user_state = os.listdir(path2)

columns5 ={'states':[],'years':[],'quarters':[],'District_Name':[],'RegisteredUsers':[],'AppOpens':[]}

for state in map_user_state:
    current_states = os.path.join(path2,state)
    map_user_year = os.listdir(current_states)
    
    for year in map_user_year:
        current_year = os.path.join(current_states,year)
        map_user_file = os.listdir(current_year)
        
        for file in map_user_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            p2 = json.load(data)
            
            for i in p2['data']['hoverData'].items():
                district_name = i[0]
                registeredusers = i[1]['registeredUsers']
                appopens =i[1]['appOpens']
                columns5['District_Name'].append(district_name)
                columns5['RegisteredUsers'].append(registeredusers)
                columns5['AppOpens'].append(appopens)
                columns5['states'].append(state)
                columns5['years'].append(year)
                columns5['quarters'].append(int(file.strip('.json')))
                
map_user = pd.DataFrame(columns5)
map_user['states']=map_user['states'].str.replace('-',' ')
map_user['states']=map_user['states'].str.title()
map_user['states']=map_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

In [7]:
#map_insurance
path3 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/map/insurance/hover/country/india/state"
map_insur_state = os.listdir(path3)

columns6 ={'states':[],'years':[],'quarters':[],'District_Name':[],'Transaction_count':[],'Transaction_amount':[]}

for state in map_insur_state:
    current_states = os.path.join(path3,state)
    map_insur_year = os.listdir(current_states)
    
    for year in map_insur_year:
        current_year = os.path.join(current_states,year)
        map_insur_file = os.listdir(current_year)
        
        for file in map_insur_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            p3 = json.load(data)
            
            for i in p3['data']['hoverDataList']:
                district_name = i['name']
                count = i['metric'][0]['count']
                amount =i['metric'][0]['amount']
                columns6['District_Name'].append(district_name)
                columns6['Transaction_count'].append(count)
                columns6['Transaction_amount'].append(amount)
                columns6['states'].append(state)
                columns6['years'].append(year)
                columns6['quarters'].append(int(file.strip('.json')))
                
map_insurance = pd.DataFrame(columns6)
map_insurance['states']=map_insurance['states'].str.replace('-',' ')
map_insurance['states']=map_insurance['states'].str.title()
map_insurance['states']=map_insurance['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

# Top

In [8]:
#Top_transaction

doc1 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/top/transaction/country/india/state"
top_tran_state = os.listdir(doc1)

columns7 ={'states':[],'years':[],'quarters':[],'Pincode':[],'Transaction_count':[],'Transaction_amount':[]}

for state in top_tran_state:
    current_states = os.path.join(doc1,state)
    top_tran_year = os.listdir(current_states)
    
    for year in top_tran_year:
        current_year = os.path.join(current_states,year)
        top_tran_file = os.listdir(current_year)
        
        for file in top_tran_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            d1 = json.load(data)
            
            for i in d1['data']['pincodes']:
                entity_name = i['entityName']
                count = i['metric']['count']
                amount =i['metric']['amount']
                columns7['Pincode'].append(entity_name)
                columns7['Transaction_count'].append(count)
                columns7['Transaction_amount'].append(amount)
                columns7['states'].append(state)
                columns7['years'].append(year)
                columns7['quarters'].append(int(file.strip('.json')))
                
top_transaction = pd.DataFrame(columns7)
top_transaction['states']=top_transaction['states'].str.replace('-',' ')
top_transaction['states']=top_transaction['states'].str.title()
top_transaction['states']=top_transaction['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

In [9]:
#Top_user
doc2 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/top/user/country/india/state"
top_user_state = os.listdir(doc2)

columns8 ={'states':[],'years':[],'quarters':[],'Pincode':[],'RegisteredUsers':[]}

for state in top_user_state:
    current_states = os.path.join(doc2,state)
    top_user_year = os.listdir(current_states)
    
    for year in top_user_year:
        current_year = os.path.join(current_states,year)
        top_user_file = os.listdir(current_year)
        
        for file in top_user_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            d2 = json.load(data)
            
            for i in d2['data']['pincodes']:
                entity_name = i['name']
                registeredUsers = i['registeredUsers']
                columns8['Pincode'].append(entity_name)
                columns8['RegisteredUsers'].append(registeredUsers)
                columns8['states'].append(state)
                columns8['years'].append(year)
                columns8['quarters'].append(int(file.strip('.json')))
                
top_user = pd.DataFrame(columns8)
top_user['states']=top_user['states'].str.replace('-',' ')
top_user['states']=top_user['states'].str.title()
top_user['states']=top_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

In [10]:
#Top_insurance
doc3 = "C:/Users/dhuwa/Downloads/project folder/phonepe/pulse/data/top/insurance/country/india/state"
top_insur_state = os.listdir(doc3)

columns9 ={'states':[],'years':[],'quarters':[],'Pincode':[],'Transaction_count':[],'Transaction_amount':[]}

for state in top_insur_state:
    current_states = os.path.join(doc3,state)
    top_insur_year = os.listdir(current_states)
    
    for year in top_insur_year:
        current_year = os.path.join(current_states,year)
        top_insur_file = os.listdir(current_year)
        
        for file in top_insur_file:
            current_file = os.path.join(current_year,file)
            data = open(current_file)
            
            d3 = json.load(data)
            
            for i in d3['data']['pincodes']:
                entity_name = i['entityName']
                count = i['metric']['count']
                amount =i['metric']['amount']
                columns9['Pincode'].append(entity_name)
                columns9['Transaction_count'].append(count)
                columns9['Transaction_amount'].append(amount)
                columns9['states'].append(state)
                columns9['years'].append(year)
                columns9['quarters'].append(int(file.strip('.json')))
                
top_insurance = pd.DataFrame(columns9)
top_insurance['states']=top_insurance['states'].str.replace('-',' ')
top_insurance['states']=top_insurance['states'].str.title()
top_insurance['states']=top_insurance['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu',' Dadra and Nagar Haveli and Daman and Diu')

In [11]:
#sql connection

myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871")
cur=myconnection.cursor()
cur.execute("create database if not exists phonepe")

1

In [12]:
#agg_transaction_table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table1 = """create table if not exists aggregated_transaction(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        Transaction_type varchar(100),
                                                                        Transaction_count BIGINT,
                                                                        Transaction_amount BIGINT)"""

cur.execute(create_table1)
myconnection.commit()

insert_table1 = """insert into aggregated_transaction(states,years,quarters,
                                                        Transaction_type,
                                                        Transaction_count,
                                                        Transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add1 = agg_transaction.values.tolist()
cur.executemany(insert_table1,add1)
myconnection.commit()

In [13]:
#agg_user table

myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table2 = """create table if not exists aggregated_user(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        Brand varchar(100),
                                                                        Transaction_count BIGINT,
                                                                        Percentage BIGINT)"""

cur.execute(create_table2)
myconnection.commit()

insert_table2 = """insert into aggregated_user(states,years,quarters,
                                                        Brand,
                                                        Transaction_count,
                                                        Percentage)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add2 = agg_user.values.tolist()
cur.executemany(insert_table2,add2)
myconnection.commit()

In [14]:
#agg_insurance table

myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table3 = """create table if not exists aggregated_insurance(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        Transaction_type varchar(100),
                                                                        Transaction_count BIGINT,
                                                                        Transaction_amount BIGINT)"""

cur.execute(create_table3)
myconnection.commit()

insert_table3 = """insert into aggregated_insurance(states,years,quarters,
                                                        Transaction_type,
                                                        Transaction_count,
                                                        Transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add3 = agg_insurance.values.tolist()
cur.executemany(insert_table3,add3)
myconnection.commit()

In [15]:
# map_transaction table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table4 = """create table if not exists map_transaction(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        District_Name varchar(100),
                                                                        Transaction_count BIGINT,
                                                                        Transaction_amount BIGINT)"""

cur.execute(create_table4)
myconnection.commit()

insert_table4 = """insert into map_transaction(states,years,quarters,
                                                        District_Name,
                                                        Transaction_count,
                                                        Transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add4 = map_transaction.values.tolist()
cur.executemany(insert_table4,add4)
myconnection.commit()

In [16]:
# map_user table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table5 = """create table if not exists map_user(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        District_Name varchar(100),
                                                                        RegisteredUsers BIGINT,
                                                                        AppOpens BIGINT)"""

cur.execute(create_table5)
myconnection.commit()

insert_table5 = """insert into map_user(states,years,quarters,
                                                        District_Name,
                                                        RegisteredUsers,
                                                        AppOpens)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add5 = map_user.values.tolist()
cur.executemany(insert_table5,add5)
myconnection.commit()

In [17]:
# map_insurance table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table6 = """create table if not exists map_insurance(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        District_Name varchar(100),
                                                                        Transaction_count BIGINT,
                                                                        Transaction_amount BIGINT)"""

cur.execute(create_table6)
myconnection.commit()

insert_table6 = """insert into map_insurance(states,years,quarters,
                                                        District_Name,
                                                        Transaction_count,
                                                        Transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add6 = map_insurance.values.tolist()
cur.executemany(insert_table6,add6)
myconnection.commit()

In [18]:
#Top_transaction table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table7 = """create table if not exists top_transaction(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        Pincode BIGINT,
                                                                        Transaction_count BIGINT,
                                                                        Transaction_amount BIGINT)"""

cur.execute(create_table7)
myconnection.commit()

insert_table7 = """insert into top_transaction(states,years,quarters,
                                                        Pincode,
                                                        Transaction_count,
                                                        Transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add7 = top_transaction.values.tolist()
cur.executemany(insert_table7,add7)
myconnection.commit()

In [19]:
#Top_user table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table8 = """create table if not exists top_user(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        Pincode BIGINT,
                                                                        RegisteredUsers BIGINT)"""

cur.execute(create_table8)
myconnection.commit()

insert_table8 = """insert into top_user(states,years,quarters,
                                                        Pincode,
                                                        RegisteredUsers)
                                                        
                                                        values(%s,%s,%s,%s,%s)"""

add8 = top_user.values.tolist()
cur.executemany(insert_table8,add8)
myconnection.commit()

In [20]:
#Top_insurance table
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

create_table9 = """create table if not exists top_insurance(states varchar(50),years INT,
                                                                        quarters INT,
                                                                        Pincode BIGINT,
                                                                        Transaction_count BIGINT,
                                                                        Transaction_amount BIGINT)"""

cur.execute(create_table9)
myconnection.commit()

insert_table9 = """insert into top_insurance(states,years,quarters,
                                                        Pincode,
                                                        Transaction_count,
                                                        Transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)"""

add9 = top_insurance.values.tolist()
cur.executemany(insert_table9,add9)
myconnection.commit()

In [2]:
myconnection=pymysql.connect(host="127.0.0.1",user="root",password="Datascience@2871",database="phonepe")
cur=myconnection.cursor()

#Aggregated_transaction
cur.execute("select * from aggregated_transaction")
myconnection.commit()
table1 = cur.fetchall()
Aggre_transaction = pd.DataFrame(table1,columns = ("States", "Years", "Quarter", "Transaction_type", "Transaction_count", "Transaction_amount"))

#Aggregated_user
cur.execute("select * from aggregated_user")
myconnection.commit()
table2 = cur.fetchall()
Aggre_user = pd.DataFrame(table2,columns = ("States", "Years", "Quarter", "Brands", "Transaction_count", "Percentage"))

#Aggregated_insurance
cur.execute("select * from aggregated_insurance")
myconnection.commit()
table3 = cur.fetchall()
Aggre_insurance = pd.DataFrame(table3,columns = ("States", "Years", "Quarter", "Transaction_type", "Transaction_count","Transaction_amount"))


#Map_transaction
cur.execute("select * from map_transaction")
myconnection.commit()
table4 = cur.fetchall()
Map_transaction = pd.DataFrame(table4,columns = ("States", "Years", "Quarter", "Districts", "Transaction_count", "Transaction_amount"))
Map_transaction['Districts'] = Map_transaction['Districts'].str.replace(" district", "")
Map_transaction['Districts']=Map_transaction['Districts'].str.title()

#Map_user
cur.execute("select * from map_user")
myconnection.commit()
table5 = cur.fetchall()
Map_user = pd.DataFrame(table5,columns = ("States", "Years", "Quarter", "Districts", "RegisteredUser", "AppOpens"))
Map_user['Districts'] = Map_user['Districts'].str.replace(" district", "")
Map_user['Districts']=Map_user['Districts'].str.title()

#Map_insurance
cur.execute("select * from map_insurance")
myconnection.commit()
table6 = cur.fetchall()
Map_insurance = pd.DataFrame(table6,columns = ("States", "Years", "Quarter", "Districts", "Transaction_count","Transaction_amount"))
Map_insurance['Districts'] = Map_insurance['Districts'].str.replace(" district", "")
Map_insurance['Districts']=Map_insurance['Districts'].str.title()


#Top_transaction
cur.execute("select * from top_transaction")
myconnection.commit()
table7= cur.fetchall()
Top_transaction = pd.DataFrame(table7,columns = ("States", "Years", "Quarter", "Pincodes", "Transaction_count", "Transaction_amount"))
Top_transaction['Pincodes'] = Top_transaction['Pincodes'].astype(str).apply(lambda x: x.split('.')[0])


#Top_user
cur.execute("select * from top_user")
myconnection.commit()
table8 = cur.fetchall()
Top_user = pd.DataFrame(table8, columns = ("States", "Years", "Quarter", "Pincodes", "RegisteredUser"))
Top_user['Pincodes']=Top_user['Pincodes'].astype(str)

#Top_insurance
cur.execute("select * from top_insurance")
myconnection.commit()
table9 = cur.fetchall()
Top_insurance = pd.DataFrame(table9,columns = ("States", "Years", "Quarter", "Pincodes", "Transaction_count", "Transaction_amount"))
Top_insurance['Pincodes']=Top_insurance['Pincodes'].astype(str)